spring:
  application:
    name: G-Cloud-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans


swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: com.grazy
  title: G-Cloud-server docs
  description: G-Cloud-server docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: grazy
  contact-url: null
  contact-email: grazyup@163.com
  version: 1.0


#logging:
#  file: C:/Users/gaofu/logs/${spring.application.name}/${spring.application.name}.log
#  level:
#    root: INFO